/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package billingmanagement.system;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.HeadlessException;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.math.BigInteger;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.time.format.DateTimeFormatter;
import java.time.LocalTime;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author dhruv
 */
public class Billing extends javax.swing.JFrame {
    Connection con;
    ResultSet rs;
    Statement st;
    int toatlamount=0;

    /**
     * Creates new form Billing
     */
    public Billing() {
        initComponents();
       SimpleDateFormat dformat=new  SimpleDateFormat("dd-MM-yyyy");
       Date date = new Date();
       lblsdate.setText(dformat.format(date));
       
       DateTimeFormatter dtf =DateTimeFormatter.ofPattern("HH:mm");
       LocalDateTime now =LocalDateTime.now();
       lblstime.setText(dtf.format(now));
      
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblsdate = new javax.swing.JLabel();
        lblstime = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtgetcontactno = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtgetname = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtgetemail = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtgetaddress = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtpid = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtPnm = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtPPrice = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtPqun = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtPdis = new javax.swing.JTextField();
        btnadd = new javax.swing.JButton();
        btnremove = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        tlbprint = new javax.swing.JTable();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txtret = new javax.swing.JTextField();
        txtpaida = new javax.swing.JTextField();
        txttotal = new javax.swing.JTextField();
        btnsave = new javax.swing.JButton();
        btntotal = new javax.swing.JButton();
        btnclose = new javax.swing.JButton();
        btnsearchbuyer = new javax.swing.JButton();
        btnregisterbuyer = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        btnPserch = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        btnpser = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(0, 0));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/billingmanagement/system/Billing ani.gif"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, -1, 103));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/billingmanagement/system/billing.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 109, 1148, 5));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Date : ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 10, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Time : ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 60, -1, -1));

        lblsdate.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblsdate.setText("Date");
        getContentPane().add(lblsdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 11, -1, -1));

        lblstime.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblstime.setText("Time");
        getContentPane().add(lblstime, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 63, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Buyer Details");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Contact No. ");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 151, -1, -1));

        txtgetcontactno.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtgetcontactno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtgetcontactnoActionPerformed(evt);
            }
        });
        getContentPane().add(txtgetcontactno, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 148, 147, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Name");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(323, 151, -1, -1));

        txtgetname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(txtgetname, new org.netbeans.lib.awtextra.AbsoluteConstraints(397, 148, 121, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Email");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(554, 151, -1, -1));

        txtgetemail.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(txtgetemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(618, 148, 149, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Address");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(814, 151, -1, -1));

        txtgetaddress.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(txtgetaddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 148, 250, -1));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 222, 1148, 10));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setText("Prouct Detail");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("Product Id");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, -1));

        txtpid.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtpid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpidActionPerformed(evt);
            }
        });
        getContentPane().add(txtpid, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, 65, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("Name");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 270, -1, -1));

        txtPnm.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtPnm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPnmActionPerformed(evt);
            }
        });
        getContentPane().add(txtPnm, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 270, 121, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setText("Price");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 270, -1, -1));

        txtPPrice.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(txtPPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 270, 80, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setText("Quantity");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 270, -1, -1));

        txtPqun.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(txtPqun, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 270, 71, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setText("Description");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 270, -1, -1));

        txtPdis.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(txtPdis, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 270, 240, -1));

        btnadd.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnadd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/billingmanagement/system/add.png"))); // NOI18N
        btnadd.setText("Add");
        btnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddActionPerformed(evt);
            }
        });
        getContentPane().add(btnadd, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 300, -1, -1));

        btnremove.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnremove.setIcon(new javax.swing.ImageIcon(getClass().getResource("/billingmanagement/system/delete.png"))); // NOI18N
        btnremove.setText("Remove");
        btnremove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnremoveActionPerformed(evt);
            }
        });
        getContentPane().add(btnremove, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 300, -1, -1));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 1148, 10));

        tlbprint.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tlbprint.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Prod_id", "Product Name", "Product Description", "product price", "Quantity", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tlbprint);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 564, 190));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel18.setText("Calculaction Details: ");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 350, -1, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel19.setText("Total :");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 400, -1, -1));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel20.setText("Paid Amount :");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 450, -1, -1));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel21.setText("Return Amount :");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 500, -1, -1));

        txtret.setEditable(false);
        txtret.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(txtret, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 500, 198, -1));

        txtpaida.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtpaida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpaidaActionPerformed(evt);
            }
        });
        getContentPane().add(txtpaida, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 450, 198, -1));

        txttotal.setEditable(false);
        txttotal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txttotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttotalActionPerformed(evt);
            }
        });
        getContentPane().add(txttotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 400, 198, -1));

        btnsave.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnsave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/billingmanagement/system/save.png"))); // NOI18N
        btnsave.setText("Save");
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });
        getContentPane().add(btnsave, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 400, -1, -1));

        btntotal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btntotal.setText("= Total");
        btntotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntotalActionPerformed(evt);
            }
        });
        getContentPane().add(btntotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 450, -1, -1));

        btnclose.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnclose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/billingmanagement/system/close Jframe.png"))); // NOI18N
        btnclose.setText("Close");
        btnclose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncloseActionPerformed(evt);
            }
        });
        getContentPane().add(btnclose, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 500, -1, -1));

        btnsearchbuyer.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnsearchbuyer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/billingmanagement/system/search.png"))); // NOI18N
        btnsearchbuyer.setText("Search");
        btnsearchbuyer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsearchbuyerActionPerformed(evt);
            }
        });
        getContentPane().add(btnsearchbuyer, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 180, -1, -1));

        btnregisterbuyer.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnregisterbuyer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/billingmanagement/system/r.png"))); // NOI18N
        btnregisterbuyer.setText("Register");
        btnregisterbuyer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregisterbuyerActionPerformed(evt);
            }
        });
        getContentPane().add(btnregisterbuyer, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 180, -1, -1));

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel23.setText("Gender");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        jComboBox1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male.", "Female.", "Others." }));
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, -1, -1));

        btnPserch.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnPserch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/billingmanagement/system/search.png"))); // NOI18N
        btnPserch.setText("Search");
        btnPserch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPserchActionPerformed(evt);
            }
        });
        getContentPane().add(btnPserch, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 180, -1, -1));

        jButton8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/billingmanagement/system/search.png"))); // NOI18N
        jButton8.setText("Search");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 180, -1, -1));

        btnpser.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnpser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/billingmanagement/system/search.png"))); // NOI18N
        btnpser.setText("Search");
        btnpser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpserActionPerformed(evt);
            }
        });
        getContentPane().add(btnpser, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 300, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/billingmanagement/system/billing background.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    // close button
    private void btncloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncloseActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btncloseActionPerformed
   // contact no 
    
    private void txtgetcontactnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtgetcontactnoActionPerformed
        // TODO add your handling code here:
        long number;
        number =Long.parseLong(txtgetcontactno.getText());
        try
        {
            con=lib.getcon(this);
            st=con.createStatement();
            rs=st.executeQuery("select * from new_buyer where contactno='"+number+"'");
            if (rs.next()){
                txtgetcontactno.setText(rs.getString(2));
                txtgetname.setText(rs.getString(1));
                txtgetemail.setText(rs.getString(3));
                txtgetaddress.setText(rs.getString(4));
                jComboBox1.setSelectedItem(rs.getString(5));
                // edatible
                txtgetcontactno.setEditable(false);
                txtgetname.setEditable(false);
                txtgetemail.setEditable(false);
                txtgetaddress.setEditable(false);
                jComboBox1.setEditable(false);
                
                
                
            }
            else{
                 JOptionPane.showConfirmDialog(this,"Buyer is not registered ","not Registered",JOptionPane.OK_OPTION); 
            }
        }
        catch (Exception e)
        {}
    }//GEN-LAST:event_txtgetcontactnoActionPerformed
    // search button 
    private void btnsearchbuyerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsearchbuyerActionPerformed
        // TODO add your handling code here:
       
        String nu=txtgetcontactno.getText();
        if(lib.check(new String[]{nu})==false)
            JOptionPane.showConfirmDialog(this,"Empty fields","error",JOptionPane.ERROR_MESSAGE);
        else{
             long number;
        number = Long.parseLong(txtgetcontactno.getText());
        try
        {
            con=lib.getcon(this);
            st=con.createStatement();
            rs=st.executeQuery("select * from new_buyer where contactno='"+number+"'");
            if (rs.next()){
                txtgetcontactno.setText(rs.getString(2));
                txtgetname.setText(rs.getString(1));
                txtgetemail.setText(rs.getString(3));
                txtgetaddress.setText(rs.getString(4));
                jComboBox1.setSelectedItem(rs.getString(5));
                // edatible
                txtgetcontactno.setEditable(false);
                txtgetname.setEditable(false);
                txtgetemail.setEditable(false);
                txtgetaddress.setEditable(false);
                jComboBox1.setEditable(false);
                
                
                
            }
            else{
                 JOptionPane.showConfirmDialog(this,"Buyer is not registered ","not Registered",JOptionPane.OK_OPTION); 
            }
        }
        catch (Exception e)
        {}
        
        }
    }//GEN-LAST:event_btnsearchbuyerActionPerformed
    // register button 
    private void btnregisterbuyerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregisterbuyerActionPerformed
        // TODO add your handling code here:
        
        String cn=txtgetcontactno.getText();
        String nam=txtgetname.getText();
        String ema=txtgetemail.getText();
        String adde=txtgetaddress.getText();
        String gen1=jComboBox1.getSelectedItem()+"";
     if(lib.check(new String[]{cn,nam,ema,adde,gen1})==false)
            JOptionPane.showConfirmDialog(this,"Please enter the fields","error",JOptionPane.ERROR_MESSAGE);
        else
        {
            long number;
            number =Long.parseLong(txtgetcontactno.getText()) ;
          try
          {
            con=lib.getcon(this);
            st=con.createStatement();
            rs=st.executeQuery("select contactno from new_buyer where contactno='"+number+"'");
            // value is find 
            if (rs.next()){
                JOptionPane.showConfirmDialog(this,"Buyer is registered ","Registered",JOptionPane.OK_OPTION); 
                
            }
            //value is not find
            else 
            {
                 long co = Long.parseLong(txtgetcontactno.getText());
                 String nm = txtgetname.getText();
                 String em = txtgetemail.getText();
                 String add = txtgetemail.getText();
                 String gen=jComboBox1.getSelectedItem()+"";
                 try
                 {
                    int no=st.executeUpdate("insert into new_buyer (name,contactno,email,address,gender) values('"+nm+"',"+co+",'"+em+"','"+add+"','"+gen+"')");
                    if(no>0)
                    {
                        JOptionPane.showConfirmDialog(this,"values inserted", "done", JOptionPane.OK_OPTION);
                    }

                 }
                 catch(HeadlessException | SQLException e)
                 {
                    JOptionPane.showConfirmDialog(this,"insert error", "no values inserted", JOptionPane.ERROR_MESSAGE);
                 }
             
            }
          }
          catch (HeadlessException | NumberFormatException | SQLException e)
          {}
        
        }
      
    }//GEN-LAST:event_btnregisterbuyerActionPerformed

    private void txtpidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpidActionPerformed
        // TODO add your handling code here:
        try
        {
            int p_id = Integer.parseInt(txtpid.getText());
            con=lib.getcon(this);
            st=con.createStatement();
            rs=st.executeQuery("select * from new_product where prod_id='"+p_id+"'");
            
            if (rs.next()){
                txtpid.setText(rs.getString(1));
                txtPnm.setText(rs.getString(2));
                txtPPrice.setText(rs.getString(3));
                txtPqun.setText("1");
                txtPdis.setText(rs.getString(4));
                // not enable
               
                txtPnm.setEditable(false);
                txtPPrice.setEditable(false);
                txtPdis.setEditable(false);
                
            }
            else{
                 JOptionPane.showConfirmDialog(this,"product is not avalble  ","product",JOptionPane.OK_OPTION); 
                  txtpid.setText("");
                txtPnm.setText("");
                txtPPrice.setText("");
                txtPdis.setText("");
            }
        }
        catch(NumberFormatException | SQLException e)
        {}
        
    }//GEN-LAST:event_txtpidActionPerformed

    private void txtPnmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPnmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPnmActionPerformed
    // add button
    private void btnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddActionPerformed
        // TODO add your handling code here:
        
        if(lib.check(new String[]{txtpid.getText(),txtPnm.getText(),txtPPrice.getText(),txtPqun.getText()})==false)
        {
            JOptionPane.showConfirmDialog(this,"empty fields", "no fields", JOptionPane.ERROR_MESSAGE);
         
       
        }
        else
        {     String pid=txtpid.getText();
           String Pnm=txtPnm.getText();
           int Ppr;
            Ppr =Integer.parseInt(txtPPrice.getText());
           String Pdt=txtPdis.getText();
           String Pq=txtPqun.getText();
           int to=Ppr*Integer.parseInt(Pq);
           String data[]={pid,Pnm,Pdt,Integer.toString(Ppr),Pq,Integer.toString(to)};
           DefaultTableModel tblModel = (DefaultTableModel)tlbprint.getModel();
           tblModel.addRow(data);
           toatlamount=toatlamount+to;
           txttotal.setText(Integer.toString(toatlamount));
           
           
           
           
        }


        
    }//GEN-LAST:event_btnaddActionPerformed

    private void txttotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttotalActionPerformed
    //remove button
    private void btnremoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnremoveActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tblMode1 =(DefaultTableModel)tlbprint.getModel();
        if(tlbprint.getSelectedRow()>=0)
        {
            String sto=(String)tblMode1.getValueAt(tlbprint.getSelectedRow(),5);
            tblMode1.removeRow(tlbprint.getSelectedRow());
            tlbprint.setModel(tblMode1);
            toatlamount=toatlamount-Integer.parseInt(sto);
            txttotal.setText(Integer.toString(toatlamount));
            
        }
        else {
          
              JOptionPane.showConfirmDialog(this ,"Table is empty","no rows",JOptionPane.ERROR_MESSAGE);
             }
        

//        int i, j, row=tblMode1.getRowCount(), col=tblMode1.getColumnCount(), selectedRow=tlbprint.getSelectedRow(), totalQua=0;
//        Object data[][];
//        int cartPQua=Integer.parseInt(tblMode1.getValueAt(selectedRow, 3)+""), cartPId=Integer.parseInt(tblMode1.getValueAt(selectedRow, 0)+"");
//        try {
//            con = lib.getcon(this);
//            if(con==null || con.isClosed()) {
//                JOptionPane.showMessageDialog(this, "Failed to connect!", "Market managment", JOptionPane.WARNING_MESSAGE);
//                return;
//            }
//
//            st = con.createStatement();
//            rs = st.executeQuery("SELECT Quantity FROM products WHERE Id="+cartPId);
//            if(rs.next()==false) {
//                JOptionPane.showMessageDialog(this, "Failed to fetch quantity.", "Market managment", JOptionPane.WARNING_MESSAGE);
//                return;
//            }
//            totalQua = rs.getInt(1);
//            
//            call_st = con.prepareCall("{call update_p_qua(?,?)}");
//            call_st.setInt(1, totalQua+cartPQua);
//            call_st.setInt(2, cartPId);
//            call_st.execute();
//            if(call_st.getUpdateCount()==0) {
//                JOptionPane.showMessageDialog(this, "Failed to update quantity.", "Market managment", JOptionPane.WARNING_MESSAGE);
//                return;
//            }
//            
//            data = new Object[row-1][col];
//            int flag=0;
//            for(i=0; i<row; i++) {
//                if(i==selectedRow) {
//                    flag=1;
//                    continue;
//                }
//                for(j=0; j<col; j++) {
//                    data[i-flag][j] = tblMode1.getValueAt(i, j);
//                }
//            }
//            lib.fillTable(this, tlbprint, data);
//        }
//        catch(Exception e) {
//            JOptionPane.showMessageDialog(this, "btnDeleteActionPerformed : "+e, "Market managment", JOptionPane.WARNING_MESSAGE);
//        }
    }//GEN-LAST:event_btnremoveActionPerformed

    private void txtpaidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpaidaActionPerformed
        // TODO add your handling code here:
        int paida= Integer.parseInt(txtpaida.getText());
        int tot = paida-toatlamount;
        txtret.setText(Integer.toString(tot));
    }//GEN-LAST:event_txtpaidaActionPerformed

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
        // TODO add your handling code here:
     if(lib.check(new String[]{txtgetcontactno.getText(),txtpid.getText(),txtpaida.getText()})==false){
         JOptionPane.showConfirmDialog(this,"empty fields","error",JOptionPane.ERROR_MESSAGE);
     }
     else
     {
         String name = txtgetname.getText();
        String cono = txtgetcontactno.getText();
        String em = txtgetemail.getText();
        String add = txtgetaddress.getText();
        String path = "C:\\billing\\";
        com.itextpdf.text.Document doc = new com.itextpdf.text.Document();
        try
        {
            PdfWriter.getInstance(doc,new FileOutputStream(path+""+name+".pdf"));
            doc.open();
            Paragraph paragraph1 = new Paragraph("                                        BCA SEM-5(BILLING MANAGEMENT SYSTEM \n\n\n");
            doc.add(paragraph1);
            Paragraph buyerdetail= new Paragraph("Date : "+lblsdate.getText()+"    Time : "+lblstime.getText()+"\nName : "+name+"\nContact No : "+cono+"\n Email : "+em+"\nAddress : "+add+"\n\n Product Detail : \n\n\n");
            doc.add(buyerdetail);
            
            PdfPTable tbl=new PdfPTable(6);
            tbl.addCell("product Id");
            tbl.addCell("Name");
            tbl.addCell("Desription");
            tbl.addCell("Price");
            tbl.addCell("Quantity");
            tbl.addCell("Sub Total");
            for(int i=0;i<tlbprint.getRowCount();i++)
            {
                String pid =tlbprint.getValueAt(i,0).toString();
                String n =tlbprint.getValueAt(i,1).toString();
                String d =tlbprint.getValueAt(i,2).toString();
                String p =tlbprint.getValueAt(i,3).toString();
                String q =tlbprint.getValueAt(i,4).toString();
                String s =tlbprint.getValueAt(i,5).toString();
                tbl.addCell(pid);
                tbl.addCell(n);
                tbl.addCell(d);
                tbl.addCell(p);
                tbl.addCell(q);
                tbl.addCell(s);
            }
            doc.add(tbl);
            Paragraph amountdetal= new Paragraph("\n Amount Detail : \n\n Total : "+txttotal.getText()+" \n Paid Amount : "+txtpaida.getText()+"\nReturn Amount :"+txtret.getText()+"\n");
            doc.add(amountdetal);
              
              
              
           doc.close(); 
           // insert data in database
           
            con=lib.getcon(this);
            st=con.createStatement();
            String bnm=txtgetname.getText();
            int cont= Integer.parseInt(txtgetcontactno.getText());
            String prod;
             prod = "";
            int tot =Integer.parseInt(txttotal.getText());
            int amt=Integer.parseInt(txtpaida.getText());
            int reta = Integer.parseInt(txtret.getText());
             for(int i=0;i<tlbprint.getRowCount();i++)
            {
               
               prod=prod.concat((String)tlbprint.getValueAt(i,2));
               prod=prod.concat(" ");
               prod=prod.concat((String)tlbprint.getValueAt(i,4));
               prod=prod.concat(" ,");
            }
         // value inaset into database
         
            int no=st.executeUpdate("insert into billing (buyer_name,buyer_co_no,product,total,amount,rerurn_am) VALUES ('"+bnm+"',"+cont+",'"+prod+"',"+tot+","+amt+","+reta+")");
               if(no>0)
               {
                     JOptionPane.showConfirmDialog(this,"values inserted", "done", JOptionPane.OK_OPTION);
               }
          //update product code
          
          for (int i=0;i<=tlbprint.getRowCount();i++)
          {
              String pid =tlbprint.getValueAt(i,0).toString();
              String tqn=(String)tlbprint.getValueAt(i,4);
              
                 rs=st.executeQuery("select quantity from new_product where prod_id="+Integer.parseInt(pid)+"");
                 if(rs.next())
                 {
                    String sq=(String)rs.getString(1);
                    int qunt=Integer.parseInt(sq)-Integer.parseInt(tqn);
                    st.executeUpdate("update new_product set quantity="+qunt+" where prod_id="+Integer.parseInt(pid)+"");
                 }
          }
            
            
            
            
        } 
        catch (FileNotFoundException | DocumentException ex) {
            Logger.getLogger(Billing.class.getName()).log(Level.SEVERE, null, ex);
                    JOptionPane.showConfirmDialog(null,ex);
                   
        } catch (SQLException ex) {
             Logger.getLogger(Billing.class.getName()).log(Level.SEVERE, null, ex);
         }
       
        
        
       
        
     }
    }//GEN-LAST:event_btnsaveActionPerformed

    private void btntotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntotalActionPerformed
        // TODO add your handling code here:
        if(lib.check(new String[]{txtpaida.getText()})==false)
        {
            JOptionPane.showConfirmDialog(this,"empty fields","error",JOptionPane.ERROR_MESSAGE);
        }
        else
        {
            int paida= Integer.parseInt(txtpaida.getText());
           int tot = paida-toatlamount;
           txtret.setText(Integer.toString(tot));
         }
    }//GEN-LAST:event_btntotalActionPerformed

    private void btnPserchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPserchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPserchActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void btnpserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpserActionPerformed
        // TODO add your handling code here:
        try
        {
            int p_id = Integer.parseInt(txtpid.getText());
            con=lib.getcon(this);
            st=con.createStatement();
            rs=st.executeQuery("select * from new_product where prod_id='"+p_id+"'");
            
            if (rs.next()){
                txtpid.setText(rs.getString(1));
                txtPnm.setText(rs.getString(2));
                txtPPrice.setText(rs.getString(3));
                txtPqun.setText("1");
                txtPdis.setText(rs.getString(4));
                // not enable
               
                txtPnm.setEditable(false);
                txtPPrice.setEditable(false);
                txtPdis.setEditable(false);
                
            }
            else{
                 JOptionPane.showConfirmDialog(this,"product is not avalble  ","product",JOptionPane.OK_OPTION); 
                  txtpid.setText("");
                txtPnm.setText("");
                txtPPrice.setText("");
                txtPdis.setText("");
            }
        }
        catch(NumberFormatException | SQLException e)
        {}
    }//GEN-LAST:event_btnpserActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Billing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Billing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Billing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Billing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Billing().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPserch;
    private javax.swing.JButton btnadd;
    private javax.swing.JButton btnclose;
    private javax.swing.JButton btnpser;
    private javax.swing.JButton btnregisterbuyer;
    private javax.swing.JButton btnremove;
    private javax.swing.JButton btnsave;
    private javax.swing.JButton btnsearchbuyer;
    private javax.swing.JButton btntotal;
    private javax.swing.JButton jButton8;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lblsdate;
    private javax.swing.JLabel lblstime;
    private javax.swing.JTable tlbprint;
    private javax.swing.JTextField txtPPrice;
    private javax.swing.JTextField txtPdis;
    private javax.swing.JTextField txtPnm;
    private javax.swing.JTextField txtPqun;
    private javax.swing.JTextField txtgetaddress;
    private javax.swing.JTextField txtgetcontactno;
    private javax.swing.JTextField txtgetemail;
    private javax.swing.JTextField txtgetname;
    private javax.swing.JTextField txtpaida;
    private javax.swing.JTextField txtpid;
    private javax.swing.JTextField txtret;
    private javax.swing.JTextField txttotal;
    // End of variables declaration//GEN-END:variables

    private void addCell(String name) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
