/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package billingmanagement.system;

import javax.swing.JOptionPane;

/**
 *
 * @author Dell
 */
public class home extends javax.swing.JFrame {
 public int tm=0;
    /**
     * Creates new form home
     */
    public home() {
        initComponents();
        btnnewbuyer.setVisible(false);
        btnupdatebuyer.setVisible(false);
        btnbuyerdetails.setVisible(false);
        btnaddemployee.setVisible(false);
        btnnewproduct.setVisible(false);
        btnupdateproduct.setVisible(false);
        btnproductdetails.setVisible(false);
        btnemployeedetail.setVisible(false);
        btnbilling.setVisible(false);
        btnbillingdetail.setVisible(false);
        btnlogout.setVisible(false);
        jLabel13.setVisible(false);
        jLabel14.setVisible(false);
        jLabel16.setVisible(false);
        jLabel17.setVisible(false);
        jLabel18.setVisible(false);
        jLabel19.setVisible(false);
        jLabel20.setVisible(false);
        jLabel21.setVisible(false);
        jLabel29.setVisible(false);
        jLabel30.setVisible(false);
        jLabel24.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        btnnewbuyer = new javax.swing.JButton();
        btnupdatebuyer = new javax.swing.JButton();
        btnbuyerdetails = new javax.swing.JButton();
        btnaddemployee = new javax.swing.JButton();
        btnnewproduct = new javax.swing.JButton();
        btnupdateproduct = new javax.swing.JButton();
        btnproductdetails = new javax.swing.JButton();
        btnemployeedetail = new javax.swing.JButton();
        btnbilling = new javax.swing.JButton();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        btnbillingdetail = new javax.swing.JButton();
        btnlogout = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/billingmanagement/system/home.PNG"))); // NOI18N
        jLabel25.setText("jLabel25");

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/billingmanagement/system/home.PNG"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1366, 768));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("New Buyer ");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setText("Update Buyer");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, -1, -1));
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(1286, 107, -1, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setText("Buyer Details");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 90, -1, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel17.setText("Add Employee");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 90, -1, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel18.setText("New Product");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 90, -1, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel19.setText("Update Product");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 90, -1, -1));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel20.setText("Product Details");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 90, -1, -1));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel21.setText("Employee Detail");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 90, -1, -1));

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(1116, 107, -1, -1));

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel24.setText("Logout");
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 90, -1, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/billingmanagement/system/control hide and show.png"))); // NOI18N
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        btnnewbuyer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/billingmanagement/system/new buyer.png"))); // NOI18N
        btnnewbuyer.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                btnnewbuyerComponentShown(evt);
            }
        });
        btnnewbuyer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnewbuyerActionPerformed(evt);
            }
        });
        getContentPane().add(btnnewbuyer, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, -1, -1));

        btnupdatebuyer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/billingmanagement/system/Update buyer.png"))); // NOI18N
        btnupdatebuyer.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                btnupdatebuyerComponentShown(evt);
            }
        });
        btnupdatebuyer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdatebuyerActionPerformed(evt);
            }
        });
        getContentPane().add(btnupdatebuyer, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, -1, -1));

        btnbuyerdetails.setIcon(new javax.swing.ImageIcon(getClass().getResource("/billingmanagement/system/buyer Details.png"))); // NOI18N
        btnbuyerdetails.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                btnbuyerdetailsComponentShown(evt);
            }
        });
        btnbuyerdetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuyerdetailsActionPerformed(evt);
            }
        });
        getContentPane().add(btnbuyerdetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, -1, -1));

        btnaddemployee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/billingmanagement/system/add-employee-icon (1).png"))); // NOI18N
        btnaddemployee.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                btnaddemployeeComponentShown(evt);
            }
        });
        btnaddemployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddemployeeActionPerformed(evt);
            }
        });
        getContentPane().add(btnaddemployee, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 10, -1, -1));

        btnnewproduct.setIcon(new javax.swing.ImageIcon(getClass().getResource("/billingmanagement/system/new product.png"))); // NOI18N
        btnnewproduct.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                btnnewproductComponentShown(evt);
            }
        });
        btnnewproduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnewproductActionPerformed(evt);
            }
        });
        getContentPane().add(btnnewproduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 10, -1, -1));

        btnupdateproduct.setIcon(new javax.swing.ImageIcon(getClass().getResource("/billingmanagement/system/update product.png"))); // NOI18N
        btnupdateproduct.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                btnupdateproductComponentShown(evt);
            }
        });
        btnupdateproduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateproductActionPerformed(evt);
            }
        });
        getContentPane().add(btnupdateproduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 10, -1, -1));

        btnproductdetails.setIcon(new javax.swing.ImageIcon(getClass().getResource("/billingmanagement/system/details product.png"))); // NOI18N
        btnproductdetails.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                btnproductdetailsComponentShown(evt);
            }
        });
        btnproductdetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnproductdetailsActionPerformed(evt);
            }
        });
        getContentPane().add(btnproductdetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 10, -1, -1));

        btnemployeedetail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/billingmanagement/system/emp.png"))); // NOI18N
        btnemployeedetail.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                btnemployeedetailComponentShown(evt);
            }
        });
        btnemployeedetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnemployeedetailActionPerformed(evt);
            }
        });
        getContentPane().add(btnemployeedetail, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 10, -1, -1));

        btnbilling.setIcon(new javax.swing.ImageIcon(getClass().getResource("/billingmanagement/system/billing.png"))); // NOI18N
        btnbilling.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                btnbillingComponentShown(evt);
            }
        });
        btnbilling.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbillingActionPerformed(evt);
            }
        });
        getContentPane().add(btnbilling, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 10, -1, -1));

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel29.setText("Billing");
        getContentPane().add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 90, -1, -1));

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel30.setText("Billing Detail");
        getContentPane().add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 90, -1, -1));

        btnbillingdetail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/billingmanagement/system/billing_detail_1_60x60.png"))); // NOI18N
        btnbillingdetail.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                btnbillingdetailComponentShown(evt);
            }
        });
        btnbillingdetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbillingdetailActionPerformed(evt);
            }
        });
        getContentPane().add(btnbillingdetail, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 10, -1, -1));

        btnlogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/billingmanagement/system/logout.png"))); // NOI18N
        btnlogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlogoutActionPerformed(evt);
            }
        });
        getContentPane().add(btnlogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 10, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/billingmanagement/system/home.PNG"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1400, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnbillingdetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbillingdetailActionPerformed
        new Billing_Detail().setVisible(true);
    }//GEN-LAST:event_btnbillingdetailActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        if(tm==0)
        {
            try
            {
                Thread.sleep(250);
                btnnewbuyer.setVisible(true);
                jLabel13.setVisible(true);
            }
            catch(Exception e)
            {
                
            }
        }
        else 
        {
            
        btnnewbuyer.setVisible(false);
        btnupdatebuyer.setVisible(false);
        btnbuyerdetails.setVisible(false);
        btnaddemployee.setVisible(false);
        btnnewproduct.setVisible(false);
        btnupdateproduct.setVisible(false);
        btnproductdetails.setVisible(false);
        btnemployeedetail.setVisible(false);
        btnbilling.setVisible(false);
        btnbillingdetail.setVisible(false);
        btnlogout.setVisible(false);
        jLabel13.setVisible(false);
        jLabel14.setVisible(false);
        jLabel16.setVisible(false);
        jLabel17.setVisible(false);
        jLabel18.setVisible(false);
        jLabel19.setVisible(false);
        jLabel20.setVisible(false);
        jLabel21.setVisible(false);
        jLabel29.setVisible(false);
        jLabel30.setVisible(false);
        jLabel24.setVisible(false);
        tm=0;
        }
        
    }//GEN-LAST:event_jButton1MouseClicked

    private void btnnewbuyerComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_btnnewbuyerComponentShown
        try
            {
                Thread.sleep(250);
                btnupdatebuyer.setVisible(true);
                jLabel14.setVisible(true);
            }
            catch(Exception e)
            {
                
            }
// TODO add your handling code here:
    }//GEN-LAST:event_btnnewbuyerComponentShown

    private void btnupdatebuyerComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_btnupdatebuyerComponentShown
        // TODO add your handling code here:
        try
            {
                Thread.sleep(250);
                btnbuyerdetails.setVisible(true);
                jLabel16.setVisible(true);
            }
            catch(Exception e)
            {
                
            }
    }//GEN-LAST:event_btnupdatebuyerComponentShown

    private void btnbuyerdetailsComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_btnbuyerdetailsComponentShown
        // TODO add your handling code here:
        try
            {
                Thread.sleep(250);
                btnaddemployee.setVisible(true);
                jLabel17.setVisible(true);
            }
            catch(Exception e)
            {
                
            }
    }//GEN-LAST:event_btnbuyerdetailsComponentShown

    private void btnaddemployeeComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_btnaddemployeeComponentShown
        // TODO add your handling code here:
        try
            {
                Thread.sleep(250);
                btnnewproduct.setVisible(true);
                jLabel18.setVisible(true);
            }
            catch(Exception e)
            {
                
            }
    }//GEN-LAST:event_btnaddemployeeComponentShown

    private void btnnewproductComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_btnnewproductComponentShown
        // TODO add your handling code here:
        try
            {
                Thread.sleep(250);
                btnupdateproduct.setVisible(true);
                jLabel19.setVisible(true);
            }
            catch(Exception e)
            {
                
            }
    }//GEN-LAST:event_btnnewproductComponentShown

    private void btnupdateproductComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_btnupdateproductComponentShown
        // TODO add your handling code here:
        try
            {
                Thread.sleep(250);
                btnproductdetails.setVisible(true);
                jLabel20.setVisible(true);
            }
            catch(Exception e)
            {
                
            }
    }//GEN-LAST:event_btnupdateproductComponentShown

    private void btnproductdetailsComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_btnproductdetailsComponentShown
        // TODO add your handling code here:
        try
            {
                Thread.sleep(250);
                btnemployeedetail.setVisible(true);
                jLabel21.setVisible(true);
            }
            catch(Exception e)
            {
                
            }
    }//GEN-LAST:event_btnproductdetailsComponentShown

    private void btnemployeedetailComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_btnemployeedetailComponentShown
        // TODO add your handling code here:
        try
            {
                Thread.sleep(250);
                btnbilling.setVisible(true);
                jLabel29.setVisible(true);
            }
            catch(Exception e)
            {
                
            }
    }//GEN-LAST:event_btnemployeedetailComponentShown

    private void btnbillingComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_btnbillingComponentShown
        // TODO add your handling code here:
        try
            {
                Thread.sleep(250);
                btnbillingdetail.setVisible(true);
                jLabel30.setVisible(true);
            }
            catch(Exception e)
            {
                
            }
    }//GEN-LAST:event_btnbillingComponentShown

    private void btnbillingdetailComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_btnbillingdetailComponentShown
        // TODO add your handling code here:try
            try
            {
                Thread.sleep(250);
                btnlogout.setVisible(true);
                jLabel24.setVisible(true);
                tm=1;
            }
            catch(Exception e)
            {
                
            }
    }//GEN-LAST:event_btnbillingdetailComponentShown

    private void btnlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlogoutActionPerformed
        // TODO add your handling code here:
        int a=JOptionPane.showConfirmDialog(null,"Do you want to logout?","select",JOptionPane.YES_NO_OPTION);
    if (a==JOptionPane.YES_OPTION)
    {
        new login().setVisible(true);// TODO add your handling code here:
    }                                   
    }//GEN-LAST:event_btnlogoutActionPerformed

    private void btnnewbuyerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnewbuyerActionPerformed
        // TODO add your handling code here:
        new NewBuyer().setVisible(true);
    }//GEN-LAST:event_btnnewbuyerActionPerformed

    private void btnupdatebuyerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdatebuyerActionPerformed
        // TODO add your handling code here:
        new Updatebuyer().setVisible(true);
    }//GEN-LAST:event_btnupdatebuyerActionPerformed

    private void btnbuyerdetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuyerdetailsActionPerformed
        // TODO add your handling code here:
        new BuyerDetails().setVisible(true);
    }//GEN-LAST:event_btnbuyerdetailsActionPerformed

    private void btnaddemployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddemployeeActionPerformed
        // TODO add your handling code here:
        new NewEmployee().setVisible(true);
    }//GEN-LAST:event_btnaddemployeeActionPerformed

    private void btnnewproductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnewproductActionPerformed
        // TODO add your handling code here:
        new NewProduct().setVisible(true);
    }//GEN-LAST:event_btnnewproductActionPerformed

    private void btnupdateproductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateproductActionPerformed
        // TODO add your handling code here:
        new UpdateProduct().setVisible(true);
    }//GEN-LAST:event_btnupdateproductActionPerformed

    private void btnproductdetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnproductdetailsActionPerformed
        // TODO add your handling code here:
        new ProductDetail().setVisible(true);
    }//GEN-LAST:event_btnproductdetailsActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnbillingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbillingActionPerformed
        // TODO add your handling code here:
        new Billing().setVisible(true);
    }//GEN-LAST:event_btnbillingActionPerformed

    private void btnemployeedetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnemployeedetailActionPerformed
        // TODO add your handling code here:
        new EmployeesDetail().setVisible(true);
    }//GEN-LAST:event_btnemployeedetailActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new home().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnaddemployee;
    private javax.swing.JButton btnbilling;
    private javax.swing.JButton btnbillingdetail;
    private javax.swing.JButton btnbuyerdetails;
    private javax.swing.JButton btnemployeedetail;
    private javax.swing.JButton btnlogout;
    private javax.swing.JButton btnnewbuyer;
    private javax.swing.JButton btnnewproduct;
    private javax.swing.JButton btnproductdetails;
    private javax.swing.JButton btnupdatebuyer;
    private javax.swing.JButton btnupdateproduct;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    // End of variables declaration//GEN-END:variables
}
