/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package billingmanagement.system;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Dell
 */
public class login extends javax.swing.JFrame {
    Connection con;
    ResultSet rs;
    Statement st;
    /**
     * Creates new form login
     */
    public login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        getUsrname = new javax.swing.JTextField();
        getPassWord = new javax.swing.JPasswordField();
        ShowPassword = new javax.swing.JCheckBox();
        loginBtn = new javax.swing.JButton();
        closebtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        selectcombo = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1650, 898));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/billingmanagement/system/login ani.gif"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 260, 291, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Password");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 470, 98, 35));

        getUsrname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getUsrname.setName(""); // NOI18N
        getContentPane().add(getUsrname, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 430, 230, -1));

        getPassWord.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getPassWord.setName(""); // NOI18N
        getContentPane().add(getPassWord, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 480, 230, -1));

        ShowPassword.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ShowPassword.setText("Show Password");
        ShowPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowPasswordActionPerformed(evt);
            }
        });
        getContentPane().add(ShowPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 540, -1, -1));

        loginBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        loginBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/billingmanagement/system/login.png"))); // NOI18N
        loginBtn.setText("Login");
        loginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtnActionPerformed(evt);
            }
        });
        getContentPane().add(loginBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 590, -1, -1));

        closebtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        closebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/billingmanagement/system/close Jframe.png"))); // NOI18N
        closebtn.setText("Close");
        closebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closebtnActionPerformed(evt);
            }
        });
        getContentPane().add(closebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 590, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("UserName");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 420, 98, 35));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Login As:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 390, -1, -1));

        selectcombo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        selectcombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Employee", "Admin" }));
        getContentPane().add(selectcombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 390, 113, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/billingmanagement/system/login background.PNG"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ShowPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowPasswordActionPerformed
        // TODO add your handling code here:
        if(ShowPassword.isSelected())
            getPassWord.setEchoChar((char)0);
        else 
            getPassWord.setEchoChar('*');
    }//GEN-LAST:event_ShowPasswordActionPerformed

    private void closebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closebtnActionPerformed
    int a=JOptionPane.showConfirmDialog(null,"Do you want to exit the application?","select",JOptionPane.YES_NO_OPTION);
    if (a==0)
    {
        System.exit(0);
    }// TODO add your handling code here:
    }//GEN-LAST:event_closebtnActionPerformed

    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed
        String usr=getUsrname.getText();
        String pwd=getPassWord.getText();
        if(lib.check(new String[]{usr,pwd})==false)
            JOptionPane.showConfirmDialog(this,"please enter the fields","enter the values",JOptionPane.ERROR_MESSAGE);
            
        else if(selectcombo.getSelectedItem().equals("Admin"))
        {
            try
            {
                con=lib.getcon(this);
                st=con.createStatement();
                rs=st.executeQuery("select * from admin where usernm='"+usr+"' and pass='"+pwd+"'");
                if(rs.next())
                {
                    new home().setVisible(true);
                    dispose();
                }
                else 
                    JOptionPane.showConfirmDialog(this,"login failed ","error",JOptionPane.ERROR_MESSAGE); 
            }
            catch(Exception e)
            {
                
            }
        }
         else if(selectcombo.getSelectedItem().equals("Employee"))
        {
            try
            {
                con=lib.getcon(this);
                st=con.createStatement();
                rs=st.executeQuery("select * from emp_detail where emp_nm='"+usr+"' and pass='"+pwd+"'");
                if(rs.next())
                {
                    new emp_home().setVisible(true);
                    dispose();
                }
                else 
                    JOptionPane.showConfirmDialog(this,"login failed ","error",JOptionPane.ERROR_MESSAGE); 
            }
            catch(Exception e)
            {
                
            }
        }
        
    }//GEN-LAST:event_loginBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox ShowPassword;
    private javax.swing.JButton closebtn;
    private javax.swing.JPasswordField getPassWord;
    private javax.swing.JTextField getUsrname;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton loginBtn;
    private javax.swing.JComboBox<String> selectcombo;
    // End of variables declaration//GEN-END:variables
}
