/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package billingmanagement.system;

import java.sql.Connection;
import java.sql.Statement;
import javax.swing.JOptionPane;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 *
 * @author Dell
 */
public class NewBuyer extends javax.swing.JFrame {
    Connection con;
    Statement s;
    
    /**
     * Creates new form NewBuyer
     */
    public NewBuyer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        textgetcontactno = new javax.swing.JTextField();
        txtgetname = new javax.swing.JTextField();
        txtgetemail = new javax.swing.JTextField();
        txtgetaddress = new javax.swing.JTextField();
        combogender = new javax.swing.JComboBox<>();
        btnclose = new javax.swing.JButton();
        btnsave = new javax.swing.JButton();
        btnreset = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/billingmanagement/system/all page background image.png"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(380, 160));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/billingmanagement/system/New buyer ani.gif"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 11, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/billingmanagement/system/new buyer.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 11, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 580, 10));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Name");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Contact  No.");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Email");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Address");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, -1, -1));

        textgetcontactno.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        textgetcontactno.setForeground(new java.awt.Color(102, 102, 102));
        textgetcontactno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textgetcontactnoActionPerformed(evt);
            }
        });
        getContentPane().add(textgetcontactno, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, 250, 30));

        txtgetname.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtgetname.setForeground(new java.awt.Color(102, 102, 102));
        getContentPane().add(txtgetname, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, 250, 30));

        txtgetemail.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtgetemail.setForeground(new java.awt.Color(102, 102, 102));
        getContentPane().add(txtgetemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, 250, 30));

        txtgetaddress.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtgetaddress.setForeground(new java.awt.Color(102, 102, 102));
        getContentPane().add(txtgetaddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, 250, 30));

        combogender.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        combogender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male.", "Female.", "Others." }));
        combogender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combogenderActionPerformed(evt);
            }
        });
        getContentPane().add(combogender, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 270, 250, 30));

        btnclose.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnclose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/billingmanagement/system/close Jframe.png"))); // NOI18N
        btnclose.setText("Close");
        btnclose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncloseActionPerformed(evt);
            }
        });
        getContentPane().add(btnclose, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 360, 100, -1));

        btnsave.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnsave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/billingmanagement/system/save.png"))); // NOI18N
        btnsave.setText("Save");
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });
        getContentPane().add(btnsave, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, 90, -1));

        btnreset.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnreset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/billingmanagement/system/Reset.png"))); // NOI18N
        btnreset.setText("Reset");
        btnreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnresetActionPerformed(evt);
            }
        });
        getContentPane().add(btnreset, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 360, 100, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Gender");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, -1, -1));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 322, 600, 10));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/billingmanagement/system/all page background image.png"))); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void combogenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combogenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combogenderActionPerformed

    private void btncloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncloseActionPerformed
       
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_btncloseActionPerformed

    private void btnresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnresetActionPerformed
        // TODO add your handling code here:
        dispose();
        new NewBuyer().setVisible(true);
    }//GEN-LAST:event_btnresetActionPerformed

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
        // TODO add your handling code here:
        String nm=txtgetname.getText();
         
       
        String address=txtgetaddress.getText();
        String email= txtgetemail.getText();
        String gen=combogender.getSelectedItem()+"";
       // int len=jTextField1.getText().length();
        
       String regx="[a-zA-Z]+[\\s][a-zA-Z]*";
       String contactno=textgetcontactno.getText();
      // String regx = "[A-Z][a-zA-Z]*";
       String regexno= "\\d{10}";
       String regexemail="[a-z][a-z0-9._]*@[a-z0-9]+[.][a-z0-9.]*";
       Pattern pattern = Pattern.compile(regexno);
       Pattern pattern1 = Pattern.compile(regexemail);
       Pattern pattern2 = Pattern.compile(regx);
       Matcher matcher = pattern.matcher(contactno);
       Matcher matcher1 = pattern1.matcher(email);
       Matcher matcher2 = pattern2.matcher(nm);
        if(lib.check(new String[]{nm,textgetcontactno.getText(),address,email,gen})==false)
        {
            JOptionPane.showConfirmDialog(this,"empty fields", "no fields", JOptionPane.ERROR_MESSAGE);
         
       
        }
      
        else if(matcher.matches() && matcher1.matches() && matcher2.matches())
        {
            try
            {
               
                con=lib.getcon(this);
                s=con.createStatement();
                int no=s.executeUpdate("insert into new_buyer (name,contactno,email,address,gender) values('"+nm+"',"+contactno+",'"+email+"','"+address+"','"+gen+"')");
               if(no>0)
               {
                     JOptionPane.showConfirmDialog(this,"values inserted", "done", JOptionPane.OK_OPTION);
               }
                   
            }
            catch(Exception e)
            {
                e.printStackTrace();
                 JOptionPane.showConfirmDialog(this,"insert error", "no values inserted", JOptionPane.ERROR_MESSAGE);
            }
                
        }
        else 
            JOptionPane.showConfirmDialog(this,"proper values is  not inserted", "error", JOptionPane.OK_OPTION);
               
    }//GEN-LAST:event_btnsaveActionPerformed

    private void textgetcontactnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textgetcontactnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textgetcontactnoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewBuyer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewBuyer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewBuyer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewBuyer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewBuyer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnclose;
    private javax.swing.JButton btnreset;
    private javax.swing.JButton btnsave;
    private javax.swing.JComboBox<String> combogender;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField textgetcontactno;
    private javax.swing.JTextField txtgetaddress;
    private javax.swing.JTextField txtgetemail;
    private javax.swing.JTextField txtgetname;
    // End of variables declaration//GEN-END:variables
}
