    /*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package billingmanagement.system;
import java.sql.Connection;
import java.sql.Statement;
import javax.swing.*;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
/**
 *
 * @author Dell
 */
public class NewEmployee extends javax.swing.JFrame {
    Connection con;
    Statement s;
    /**
     * Creates new form NewEmployee
     */
    public NewEmployee() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtgetempname = new javax.swing.JTextField();
        txtgetempmobileno = new javax.swing.JTextField();
        txtgetempassword = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        txtgetempconfirmpass = new javax.swing.JPasswordField();
        btnsave = new javax.swing.JButton();
        btnreset = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        combogetempgender = new javax.swing.JComboBox<>();
        Gender = new javax.swing.JLabel();
        btnclose = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/billingmanagement/system/all page background image.png"))); // NOI18N
        jLabel7.setText("jLabel7");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(380, 160));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(600, 450));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Add Employee");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, 188, 90));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/billingmanagement/system/add-employee-icon (1).png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 97, 90));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Name");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 70, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Mobile NO");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 74, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Password");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 70, 30));

        txtgetempname.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(txtgetempname, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, 200, 30));

        txtgetempmobileno.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(txtgetempmobileno, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, 200, 30));
        getContentPane().add(txtgetempassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, 200, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Confirm Password");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, -1, 40));

        txtgetempconfirmpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtgetempconfirmpassActionPerformed(evt);
            }
        });
        getContentPane().add(txtgetempconfirmpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 280, 200, 30));

        btnsave.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnsave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/billingmanagement/system/save.png"))); // NOI18N
        btnsave.setText("Save");
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });
        getContentPane().add(btnsave, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, -1, 30));

        btnreset.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnreset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/billingmanagement/system/Reset.png"))); // NOI18N
        btnreset.setText("Reset");
        btnreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnresetActionPerformed(evt);
            }
        });
        getContentPane().add(btnreset, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 400, -1, 30));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/billingmanagement/system/close Jframe.png"))); // NOI18N
        jButton3.setText("Close");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1004, 758, -1, -1));

        combogetempgender.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        combogetempgender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Others" }));
        getContentPane().add(combogetempgender, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 330, 200, 30));

        Gender.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Gender.setText("Gender");
        getContentPane().add(Gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 330, 63, 30));

        btnclose.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnclose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/billingmanagement/system/close Jframe.png"))); // NOI18N
        btnclose.setText("Close");
        btnclose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncloseActionPerformed(evt);
            }
        });
        getContentPane().add(btnclose, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 400, -1, 30));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/billingmanagement/system/all page background image.png"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -70, -1, 590));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btnresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnresetActionPerformed
        // TODO add your handling code here:
        new NewEmployee().setVisible(true);
    }//GEN-LAST:event_btnresetActionPerformed

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
        // TODO add your handling code here:
        String nm=txtgetempname.getText();
        String ph=txtgetempmobileno.getText();
        String pass=txtgetempassword.getText();
        String conpass=txtgetempconfirmpass.getText();
        String gen=(String)combogetempgender.getSelectedItem();
        boolean tf;
        int count=0;
        if(pass.equals(conpass))
        tf=true;
        else
        tf=false;

        if(lib.check(new String[]{nm,ph,pass,conpass,gen})==false)
        {    JOptionPane.showConfirmDialog(this,"please enter the Fields","error",JOptionPane.ERROR_MESSAGE);
             count+=1; 
        }
        if(tf==false)
        {
            JOptionPane.showConfirmDialog(this,"Your password does not match","error",JOptionPane.ERROR_MESSAGE);
            new NewEmployee().setVisible(true);
            dispose();
        }
        else if(ph.matches("\\d{10}") && nm.matches("[a-zA-Z]+[\\s][a-zA-Z]*"))
        {
            long ph1=Long.parseLong(txtgetempmobileno.getText());
            try
            {
                con=lib.getcon(this);
                s=con.createStatement();
                int no=s.executeUpdate("insert into emp_detail(emp_nm,mobileno,pass,gender) values('"+nm+"',"+ph1+",'"+pass+"','"+gen+"') ");
                if(no>0)
                {
                    JOptionPane.showConfirmDialog(this,"values inserted", "done", JOptionPane.OK_OPTION);
                    new NewEmployee().setVisible(true);
                    dispose();
                }

            }
            catch(Exception e)
            {

                JOptionPane.showConfirmDialog(this,"insert error", "no values inserted", JOptionPane.ERROR_MESSAGE);
            }
        }
        else if(count==0)
        JOptionPane.showConfirmDialog(this,"Values are incorrect", "error", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_btnsaveActionPerformed

    private void txtgetempconfirmpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtgetempconfirmpassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtgetempconfirmpassActionPerformed

    private void btncloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncloseActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btncloseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewEmployee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Gender;
    private javax.swing.JButton btnclose;
    private javax.swing.JButton btnreset;
    private javax.swing.JButton btnsave;
    private javax.swing.JComboBox<String> combogetempgender;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPasswordField txtgetempassword;
    private javax.swing.JPasswordField txtgetempconfirmpass;
    private javax.swing.JTextField txtgetempmobileno;
    private javax.swing.JTextField txtgetempname;
    // End of variables declaration//GEN-END:variables
}
