/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package billingmanagement.system;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author dhruv
 */
public class UpdateProduct extends javax.swing.JFrame {
    Connection con;
    ResultSet rs;
    Statement st;

    /**
     * Creates new form UpdateProduct
     */
    public UpdateProduct() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        txtprodid = new javax.swing.JTextField();
        searchprod = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtprodname = new javax.swing.JTextField();
        txtprodprice = new javax.swing.JTextField();
        txtproddescription = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        btnupdate = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        btnclose = new javax.swing.JButton();
        btnreset = new javax.swing.JButton();
        txtprodquantity = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(380, 160));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/billingmanagement/system/update product ani.gif"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 12, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/billingmanagement/system/update product.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 11, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 82, 580, 10));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Product Id ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 101, -1, -1));

        txtprodid.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(txtprodid, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 98, 225, -1));

        searchprod.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        searchprod.setIcon(new javax.swing.ImageIcon(getClass().getResource("/billingmanagement/system/search.png"))); // NOI18N
        searchprod.setText("Search");
        searchprod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchprodActionPerformed(evt);
            }
        });
        getContentPane().add(searchprod, new org.netbeans.lib.awtextra.AbsoluteConstraints(446, 98, -1, -1));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 138, 580, 10));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Product Name");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 169, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Product Price");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 214, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Description");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 259, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Quantity");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 307, -1, -1));

        txtprodname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(txtprodname, new org.netbeans.lib.awtextra.AbsoluteConstraints(247, 166, 250, -1));

        txtprodprice.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(txtprodprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(247, 211, 250, -1));

        txtproddescription.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(txtproddescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(247, 256, 250, -1));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 364, 580, 10));

        btnupdate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnupdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/billingmanagement/system/save.png"))); // NOI18N
        btnupdate.setText("Update");
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });
        getContentPane().add(btnupdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, -1, -1));

        btndelete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btndelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/billingmanagement/system/Reset.png"))); // NOI18N
        btndelete.setText("Delete");
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btndelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 400, -1, -1));

        btnclose.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnclose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/billingmanagement/system/close Jframe.png"))); // NOI18N
        btnclose.setText("Close");
        btnclose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncloseActionPerformed(evt);
            }
        });
        getContentPane().add(btnclose, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 400, -1, -1));

        btnreset.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnreset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/billingmanagement/system/Reset.png"))); // NOI18N
        btnreset.setText("Reset");
        btnreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnresetActionPerformed(evt);
            }
        });
        getContentPane().add(btnreset, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 400, -1, -1));

        txtprodquantity.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(txtprodquantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(247, 307, 250, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/billingmanagement/system/all page background image.png"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btncloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncloseActionPerformed
        // TODO add your handling code here:
        //close button
        dispose();
    }//GEN-LAST:event_btncloseActionPerformed

    private void searchprodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchprodActionPerformed
        // TODO add your handling code here:
        // search button
        int pid=Integer.parseInt(txtprodid.getText());
          try
            {
                con=lib.getcon(this);
                st=con.createStatement();
                rs=st.executeQuery("select * from new_product where prod_id='"+pid+"'");
                if(rs.next())
                {
                    txtprodid.setEditable(false);
                    txtprodname.setText(rs.getString(2));
                    txtprodprice.setText(rs.getString(3));
                    txtproddescription.setText(rs.getString(4));
                    txtprodquantity.setText(rs.getString(5));
                    
                }
                else 
                {
                     JOptionPane.showConfirmDialog(this,"No such number was found","error",JOptionPane.OK_OPTION); 
                }
            }      
            catch(Exception e)
            {
                
            }
    }//GEN-LAST:event_searchprodActionPerformed
     //Upadte Button
    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
        // TODO add your handling code here:
        String id1=txtprodid.getText();
        String n1=txtprodname.getText();
        String  p1=txtprodprice.getText();
        String d1=txtproddescription.getText();
        String quant=txtprodquantity.getText();
        if(lib.check(new String[] {id1,n1,p1,d1,d1,quant})==false)
        {
            JOptionPane.showConfirmDialog(this,"empty fields","error",JOptionPane.ERROR_MESSAGE);
        }
        else
        {
        try
        {
                con=lib.getcon(this);
                st=con.createStatement();
                int no=st.executeUpdate("update new_product set prod_name='"+n1+"',prod_price="+p1+",description='"+d1+"',quantity="+Integer.parseInt(quant)+" where prod_id="+id1+"");
                JOptionPane.showConfirmDialog(this,""+no+" record(s) updated","updated",JOptionPane.OK_OPTION); 
                if(no>=0)
                {
                    txtprodid.setText("");
                    txtprodname.setText("");
                    txtprodprice.setText("");
                    txtproddescription.setText("");
                    txtprodquantity.setText("");
                    txtprodid.setEditable(true);
                }
        }
        catch(Exception e)
        {
            
        }
        }
    }//GEN-LAST:event_btnupdateActionPerformed
    // delete button
    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        // TODO add your handling code here:
         
        String id=txtprodid.getText();
        String n1=txtprodname.getText();
        String  p1=txtprodprice.getText();
        String d1=txtproddescription.getText();
        String quant=txtprodquantity.getText();
        if(lib.check(new String[]{id,n1,p1,d1,quant})==false)
            JOptionPane.showConfirmDialog(this,"Empty fields","error",JOptionPane.ERROR_MESSAGE);
        else{
            int id1=Integer.parseInt(txtprodid.getText());
        try
        {
            con=lib.getcon(this);
            st=con.createStatement();
            int no=st.executeUpdate("delete from new_product where prod_id="+id1+"");
            JOptionPane.showConfirmDialog(this,""+no+" record(s) deleted","deleted",JOptionPane.OK_OPTION); 
            if(no>=0)
                {
                    txtprodid.setText("");
                    txtprodname.setText("");
                    txtprodprice.setText("");
                    txtproddescription.setText("");
                    txtprodquantity.setText("");
                    txtprodid.setEditable(true);
                }
        } 
        catch (SQLException ex) {
            Logger.getLogger(UpdateProduct.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
    }//GEN-LAST:event_btndeleteActionPerformed
    //Reset Button
    private void btnresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnresetActionPerformed
        // TODO add your handling code here:
        txtprodid.setEditable(true);
        txtprodid.setText("");
        txtprodname.setText("");
        txtprodprice.setText("");
        txtproddescription.setText("");
        txtprodquantity.setText("");
        
    }//GEN-LAST:event_btnresetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateProduct().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnclose;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btnreset;
    private javax.swing.JButton btnupdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JButton searchprod;
    private javax.swing.JTextField txtproddescription;
    private javax.swing.JTextField txtprodid;
    private javax.swing.JTextField txtprodname;
    private javax.swing.JTextField txtprodprice;
    private javax.swing.JTextField txtprodquantity;
    // End of variables declaration//GEN-END:variables
}
