

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package billingmanagement.system;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import java.util.regex.Matcher;
import java.util.regex.Pattern;


/**
 *
 * @author dhruv
 */
public class Updatebuyer extends javax.swing.JFrame {
     Connection con;
    ResultSet rs;
    Statement st;
    /**
     * Creates new form 
     */
    public Updatebuyer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btncontactno = new javax.swing.JTextField();
        btnsearchbuyer = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        txtupdatename = new javax.swing.JTextField();
        txtupdateemail = new javax.swing.JTextField();
        txtupdateadd = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        btnupdate = new javax.swing.JButton();
        btnreset = new javax.swing.JButton();
        btnclose = new javax.swing.JButton();
        combodender = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/billingmanagement/system/all page background image.png"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(380, 160));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/billingmanagement/system/Update buyer.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/billingmanagement/system/update buyer ani.gif"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 11, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 77, 580, 10));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Contact No.");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 111, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Name");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 183, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Email");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Address");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Gender");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 340, -1, -1));

        btncontactno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncontactnoActionPerformed(evt);
            }
        });
        getContentPane().add(btncontactno, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 111, 180, -1));

        btnsearchbuyer.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnsearchbuyer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/billingmanagement/system/search.png"))); // NOI18N
        btnsearchbuyer.setText("Search");
        btnsearchbuyer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsearchbuyerActionPerformed(evt);
            }
        });
        getContentPane().add(btnsearchbuyer, new org.netbeans.lib.awtextra.AbsoluteConstraints(432, 105, -1, -1));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 152, 580, 10));

        txtupdatename.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(txtupdatename, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, 250, -1));

        txtupdateemail.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(txtupdateemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 230, 250, -1));

        txtupdateadd.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtupdateadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtupdateaddActionPerformed(evt);
            }
        });
        getContentPane().add(txtupdateadd, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 280, 250, -1));
        getContentPane().add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 385, 580, 10));

        btnupdate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnupdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/billingmanagement/system/save.png"))); // NOI18N
        btnupdate.setText("Update");
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });
        getContentPane().add(btnupdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 406, -1, -1));

        btnreset.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnreset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/billingmanagement/system/Reset.png"))); // NOI18N
        btnreset.setText("Reset");
        btnreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnresetActionPerformed(evt);
            }
        });
        getContentPane().add(btnreset, new org.netbeans.lib.awtextra.AbsoluteConstraints(256, 406, -1, -1));

        btnclose.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnclose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/billingmanagement/system/close Jframe.png"))); // NOI18N
        btnclose.setText("Close");
        btnclose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncloseActionPerformed(evt);
            }
        });
        getContentPane().add(btnclose, new org.netbeans.lib.awtextra.AbsoluteConstraints(451, 406, -1, -1));

        combodender.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        combodender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Others." }));
        getContentPane().add(combodender, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 330, 260, 30));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/billingmanagement/system/all page background image.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtupdateaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtupdateaddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtupdateaddActionPerformed

    private void btncloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncloseActionPerformed
        // TODO add your handling code here:
        //close button
    
        dispose();
    }//GEN-LAST:event_btncloseActionPerformed

    private void btnresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnresetActionPerformed
        // TODO add your handling code here:
        //reset button
        new Updatebuyer().setVisible(true);
        setVisible(false);
       
    }//GEN-LAST:event_btnresetActionPerformed

    private void btnsearchbuyerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsearchbuyerActionPerformed
        // TODO add your handling code here:
        String contactno=btncontactno.getText();
         if(lib.check(new String[]{contactno})==false)
            JOptionPane.showConfirmDialog(this,"empty fields","error",JOptionPane.ERROR_MESSAGE);
         
         
          else
          {
              long a=Long.parseLong(btncontactno.getText());
               try
               {
                 con=lib.getcon(this);
                 st=con.createStatement();
                 rs=st.executeQuery("select * from new_buyer where contactno='"+a+"'");
                 if(rs.next())
                 {
                    btncontactno.setEditable(false);
                    txtupdatename.setText(rs.getString(1));
                   // jTextField3.setText(rs.getString(2));
                    txtupdateemail.setText(rs.getString(3));
                    txtupdateadd.setText(rs.getString(4));
                    combodender.setSelectedItem(rs.getString(5));
                 }
                 else 
                 {
                     JOptionPane.showConfirmDialog(this,"No such number was found","error",JOptionPane.OK_OPTION); 
                 }
                }      
                catch(Exception e)
                {
                
                }
          }
    }//GEN-LAST:event_btnsearchbuyerActionPerformed

    private void btncontactnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncontactnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btncontactnoActionPerformed
    //update button
    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
        // TODO add your handling code here:
        
        String n1=txtupdatename.getText();
        String contactno=btncontactno.getText();
        String e1=txtupdateemail.getText();
        String a1=txtupdateadd.getText();
        String g1=(String)combodender.getSelectedItem();
        
        
       String regexemail1="[a-z][a-z0-9._]*@[a-z0-9]+[.][a-z0-9.]*" ;
       String regexname="[a-zA-Z]+[\\s][a-zA-Z]*";
     
      
       Pattern pattern2 = Pattern.compile(regexname);
       Pattern pattern3=Pattern.compile(regexemail1);
       
         Matcher matcher3=pattern3.matcher(e1);
         Matcher matcher2=pattern2.matcher(n1);
      
 
       
       
        if(lib.check(new String[]{n1,contactno,e1,a1,g1})==false)
            JOptionPane.showConfirmDialog(this,"empty fields","error",JOptionPane.ERROR_MESSAGE);
        else if (matcher2.matches()&&matcher3.matches() ){
             Long c1=Long.parseLong(btncontactno.getText()); 
            try
            {
                con=lib.getcon(this);
                st=con.createStatement();
                int no=st.executeUpdate("update new_buyer set name='"+n1+"',contactno="+c1+",email='"+e1+"',address='"+a1+"',gender='"+g1+"' where contactno="+c1+"");
                JOptionPane.showConfirmDialog(this,""+no+" record(s) updated","updated",JOptionPane.OK_OPTION); 
                if(no>=0)
                {
                    btncontactno.setText("");
                    txtupdatename.setText("");
                    txtupdateemail.setText("");
                    txtupdateadd.setText("");
                    btncontactno.setEditable(true);
                }
            }
            catch(Exception e)
            {
            
            }
        }
        else
            JOptionPane.showConfirmDialog(this,"inncorrect fields","error",JOptionPane.ERROR_MESSAGE);
       
    }//GEN-LAST:event_btnupdateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Updatebuyer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Updatebuyer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Updatebuyer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Updatebuyer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Updatebuyer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnclose;
    private javax.swing.JTextField btncontactno;
    private javax.swing.JButton btnreset;
    private javax.swing.JButton btnsearchbuyer;
    private javax.swing.JButton btnupdate;
    private javax.swing.JComboBox<String> combodender;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JTextField txtupdateadd;
    private javax.swing.JTextField txtupdateemail;
    private javax.swing.JTextField txtupdatename;
    // End of variables declaration//GEN-END:variables
}
